server {
    listen       80;
    server_name  localhost;
    absolute_redirect off;

    charset utf8;
    client_max_body_size 10M;

    set_real_ip_from    0.0.0.0/0;
    real_ip_header      X-Forwarded-For;
    real_ip_recursive   on;

    location / {
        alias /app/;
        try_files $uri $uri/ /index.html;
    }

    #BASE_LOCATION

    location /shm {
        proxy_read_timeout 300s;
        proxy_set_header Host $proxy_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_ssl_server_name on;
        proxy_pass #SHM_URL;
        #proxy_cookie_path;
    }

    location /remna-api/ {
        proxy_read_timeout 30s;
        proxy_set_header Host $proxy_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        # Caddy security: X-Api-Key — ключ из портала Caddy (/settings/apikeys)
        proxy_set_header X-Api-Key "#REMNA_CADDY_API_KEY";
        proxy_set_header X-Auth-Realm "local";
        # Remnawave API: Bearer токен из настроек Remnawave
        proxy_set_header Authorization "Bearer #REMNA_API_TOKEN";
        proxy_ssl_server_name on;
        rewrite ^/remna-api/(.*)$ /api/$1 break;
        proxy_pass #REMNA_URL;
    }

}
